on:
  push:
    tags:
      - "v*"

name: Create Release

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.14]
        goos: [linux, windows, darwin]
        goarch: [amd64, 386]
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags "-s -w" -o bin/s3-${{ matrix.goos }}-${{ matrix.goarch }} .
      - run: |
          curl -L https://github.com/upx/upx/releases/download/v3.95/upx-3.95-amd64_linux.tar.xz | tar -xJf -
          upx-3.95-amd64_linux/upx bin/s3-${{ matrix.goos }}-${{ matrix.goarch }}
      - run: tar -cJ bin/s3-${{ matrix.goos }}-${{ matrix.goarch }} > bin/s3-${{ matrix.goos }}-${{ matrix.goarch }}.tar.xz
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: s3-${{ matrix.goos }}-${{ matrix.goarch }}
          path: bin/s3-${{ matrix.goos }}-${{ matrix.goarch }}.tar.xz
  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - run: echo '${{ steps.create_release.outputs.upload_url }}' > upload_url.txt
      - name: Store Upload URL
        uses: actions/upload-artifact@v1
        with:
          name: release-upload-url
          path: upload_url.txt
  upload:
    name: Upload Assets
    runs-on: ubuntu-latest
    needs: release
    strategy:
      matrix:
        go: [1.14]
        goos: [linux, windows, darwin]
        goarch: [amd64, 386]
    steps:
      - name: Download Upload URL
        uses: actions/download-artifact@v1
        with:
          name: release-upload-url
      - run: echo "::set-output name=upload_url::`cat release-upload-url/upload_url.txt`"
        id: output_url
      - name: Download
        uses: actions/download-artifact@v1
        with:
          name: s3-${{ matrix.goos }}-${{ matrix.goarch }}
      - name: Upload Release Asset
        if: steps.output_url.outputs.upload_url
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.output_url.outputs.upload_url }}
          asset_path: s3-${{ matrix.goos }}-${{ matrix.goarch }}/s3-${{ matrix.goos }}-${{ matrix.goarch }}.tar.xz
          asset_name: s3-${{ matrix.goos }}-${{ matrix.goarch }}.tar.xz
          asset_content_type: application/x-xz
